# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gibb sampling
#'
#' @param N  integer.
#' @param thin integer
#' @export gibbs_cpp
#'
gibbs_cpp <- function(N, thin) {
    .Call('_scGPS_gibbs_cpp', PACKAGE = 'scGPS', N, thin)
}

#' Calculate mean
#'
#' @param N  integer.
#' @param thin integer
#' @export gibbs_cpp
#'
muRcpp <- function(x) {
    .Call('_scGPS_muRcpp', PACKAGE = 'scGPS', x)
}

#' Calculate variance
#'
#' @param N  integer.
#' @param thin integer
#' @export gibbs_cpp
#'
varRcpp <- function(x, bias = TRUE) {
    .Call('_scGPS_varRcpp', PACKAGE = 'scGPS', x, bias)
}

